// Hematology department — 40 tests
const hematology = {
  id: "hematology",
  name: "Hematology",
  tests: [
    { id: "hematology_1",  name: "Hemoglobin", parameter: "Hemoglobin", unit: "g/dL", normalMin: 13.5, normalMax: 17.5, description: "Hemoglobin concentration (adult male ref range)" },
    { id: "hematology_2",  name: "RBC Count", parameter: "RBC", unit: "million/µL", normalMin: 4.5, normalMax: 6.0, description: "Red blood cell count" },
    { id: "hematology_3",  name: "WBC Count", parameter: "WBC", unit: "cells/µL", normalMin: 4000, normalMax: 11000, description: "White blood cell count" },
    { id: "hematology_4",  name: "Platelet Count", parameter: "Platelets", unit: "cells/µL", normalMin: 150000, normalMax: 450000, description: "Platelet count" },
    { id: "hematology_5",  name: "Hematocrit (PCV)", parameter: "Hct", unit: "%", normalMin: 40, normalMax: 52, description: "Packed cell volume / hematocrit (adult male typical range)" },
    { id: "hematology_6",  name: "MCV (Mean Corpuscular Volume)", parameter: "MCV", unit: "fL", normalMin: 80, normalMax: 100, description: "Average red cell volume" },
    { id: "hematology_7",  name: "MCH (Mean Corpuscular Hemoglobin)", parameter: "MCH", unit: "pg", normalMin: 27, normalMax: 33, description: "Average hemoglobin per red cell" },
    { id: "hematology_8",  name: "MCHC (Mean Corpuscular Hemoglobin Concentration)", parameter: "MCHC", unit: "g/dL", normalMin: 32, normalMax: 36, description: "Hemoglobin concentration in red cells" },
    { id: "hematology_9",  name: "RDW (Red Cell Distribution Width)", parameter: "RDW", unit: "%", normalMin: 11.5, normalMax: 14.5, description: "Variation in red cell size" },
    { id: "hematology_10", name: "Peripheral Blood Film", parameter: "Morphology", unit: "", normalMin: 0, normalMax: 0, description: "Microscopy report: RBC/WBC/platelet morphology" },
    { id: "hematology_11", name: "ESR (Erythrocyte Sedimentation Rate)", parameter: "ESR", unit: "mm/hr", normalMin: 0, normalMax: 20, description: "Inflammation marker (adult reference: men 0-15, women 0-20 mm/hr)" },
    { id: "hematology_12", name: "Reticulocyte Count", parameter: "Reticulocytes", unit: "%", normalMin: 0.5, normalMax: 1.5, description: "Young red blood cells percentage" },
    { id: "hematology_13", name: "MPV (Mean Platelet Volume)", parameter: "MPV", unit: "fL", normalMin: 7.5, normalMax: 11.5, description: "Average platelet size" },
    { id: "hematology_14", name: "PDW (Platelet Distribution Width)", parameter: "PDW", unit: "%", normalMin: 9, normalMax: 17, description: "Variation in platelet size" },
    { id: "hematology_15", name: "Absolute Neutrophil Count (ANC)", parameter: "ANC", unit: "cells/µL", normalMin: 1500, normalMax: 8000, description: "Absolute neutrophil count" },
    { id: "hematology_16", name: "Absolute Lymphocyte Count", parameter: "ALC", unit: "cells/µL", normalMin: 1000, normalMax: 4800, description: "Absolute lymphocyte count" },
    { id: "hematology_17", name: "Absolute Monocyte Count", parameter: "AMC", unit: "cells/µL", normalMin: 200, normalMax: 1000, description: "Absolute monocyte count" },
    { id: "hematology_18", name: "Absolute Eosinophil Count", parameter: "AEC", unit: "cells/µL", normalMin: 30, normalMax: 350, description: "Absolute eosinophil count" },
    { id: "hematology_19", name: "Neutrophils (%)", parameter: "Neutrophils", unit: "%", normalMin: 40, normalMax: 70, description: "Percentage of neutrophils" },
    { id: "hematology_20", name: "Lymphocytes (%)", parameter: "Lymphocytes", unit: "%", normalMin: 20, normalMax: 45, description: "Percentage of lymphocytes" },
    { id: "hematology_21", name: "Monocytes (%)", parameter: "Monocytes", unit: "%", normalMin: 2, normalMax: 8, description: "Percentage of monocytes" },
    { id: "hematology_22", name: "Eosinophils (%)", parameter: "Eosinophils", unit: "%", normalMin: 1, normalMax: 4, description: "Percentage of eosinophils" },
    { id: "hematology_23", name: "Basophils (%)", parameter: "Basophils", unit: "%", normalMin: 0, normalMax: 1, description: "Percentage of basophils" },
    { id: "hematology_24", name: "Bleeding Time", parameter: "Bleeding Time", unit: "min", normalMin: 2, normalMax: 7, description: "Primary hemostasis test (Ivy method typical range)" },
    { id: "hematology_25", name: "Clotting Time", parameter: "Clotting Time", unit: "min", normalMin: 5, normalMax: 15, description: "Clot formation time (capillary/venous methods vary)" },
    { id: "hematology_26", name: "Prothrombin Time (PT)", parameter: "PT", unit: "sec", normalMin: 11, normalMax: 13.5, description: "Extrinsic pathway coagulation time" },
    { id: "hematology_27", name: "INR", parameter: "INR", unit: "", normalMin: 0.8, normalMax: 1.2, description: "International Normalized Ratio" },
    { id: "hematology_28", name: "Activated Partial Thromboplastin Time (APTT)", parameter: "APTT", unit: "sec", normalMin: 25, normalMax: 35, description: "Intrinsic pathway coagulation time" },
    { id: "hematology_29", name: "Fibrinogen", parameter: "Fibrinogen", unit: "mg/dL", normalMin: 200, normalMax: 400, description: "Plasma fibrinogen concentration" },
    { id: "hematology_30", name: "D-Dimer", parameter: "D-Dimer", unit: "ng/mL", normalMin: 0, normalMax: 500, description: "Fibrin degradation product (venous thromboembolism screening)" },
    { id: "hematology_31", name: "Direct Coombs Test (DAT)", parameter: "Direct Coombs", unit: "", normalMin: 0, normalMax: 0, description: "Detects antibodies/complement on RBCs (positive/negative)" },
    { id: "hematology_32", name: "Indirect Coombs Test (IAT)", parameter: "Indirect Coombs", unit: "", normalMin: 0, normalMax: 0, description: "Antibody screening for transfusion compatibility" },
    { id: "hematology_33", name: "Blood Group (ABO)", parameter: "ABO Group", unit: "", normalMin: 0, normalMax: 0, description: "ABO blood grouping" },
    { id: "hematology_34", name: "Rh Typing", parameter: "Rh (D)", unit: "", normalMin: 0, normalMax: 0, description: "Rhesus D antigen typing" },
    { id: "hematology_35", name: "Crossmatch", parameter: "Crossmatch", unit: "", normalMin: 0, normalMax: 0, description: "Compatibility testing for transfusion" },
    { id: "hematology_36", name: "Sickle Cell Screening (Dithionate / Sickling Test)", parameter: "Sickle Screen", unit: "", normalMin: 0, normalMax: 0, description: "Sickle cell trait/disease screening (pos/neg)" },
    { id: "hematology_37", name: "Hemoglobin Electrophoresis", parameter: "Hb Electrophoresis", unit: "", normalMin: 0, normalMax: 0, description: "Hemoglobin variant analysis (HbA,HbS,HbF etc.)" },
    { id: "hematology_38", name: "Peripheral Smear - Malaria Parasite", parameter: "Malaria Smear", unit: "", normalMin: 0, normalMax: 0, description: "Microscopy for malaria parasites (thick/thin films)" },
    { id: "hematology_39", name: "Absolute Blast Count", parameter: "Blasts", unit: "cells/µL", normalMin: 0, normalMax: 0, description: "Blast cells (if suspected leukemia) - specialist reporting" },
    { id: "hematology_40", name: "Bone Marrow Examination (Report)", parameter: "Bone Marrow", unit: "", normalMin: 0, normalMax: 0, description: "Bone marrow aspirate/biopsy report (morphology & cellularity) - specialist test" }
  ]
};

// Example: to integrate, push into your departments array like:
// departmentsArray.push(hematology);
// Biochemistry / Clinical Chemistry — 40 tests
const biochemistry = {
  id: "biochemistry",
  name: "Biochemistry / Clinical Chemistry",
  tests: [
    { id: "biochem_1",  name: "Fasting Blood Sugar (FBS)", parameter: "Glucose (Fasting)", unit: "mg/dL", normalMin: 70, normalMax: 100, description: "Fasting glucose level" },
    { id: "biochem_2",  name: "Random Blood Sugar (RBS)", parameter: "Glucose (Random)", unit: "mg/dL", normalMin: 70, normalMax: 140, description: "Random glucose level" },
    { id: "biochem_3",  name: "HbA1c (Glycated Hemoglobin)", parameter: "HbA1c", unit: "%", normalMin: 4, normalMax: 5.6, description: "Average blood glucose (3 months)" },
    { id: "biochem_4",  name: "Glucose Tolerance Test (GTT)", parameter: "Glucose 2h", unit: "mg/dL", normalMin: 70, normalMax: 140, description: "Oral glucose tolerance test" },
    { id: "biochem_5",  name: "Serum Cholesterol (Total)", parameter: "Cholesterol", unit: "mg/dL", normalMin: 125, normalMax: 200, description: "Total serum cholesterol" },
    { id: "biochem_6",  name: "HDL Cholesterol", parameter: "HDL-C", unit: "mg/dL", normalMin: 40, normalMax: 60, description: "High-density lipoprotein cholesterol" },
    { id: "biochem_7",  name: "LDL Cholesterol", parameter: "LDL-C", unit: "mg/dL", normalMin: 0, normalMax: 100, description: "Low-density lipoprotein cholesterol" },
    { id: "biochem_8",  name: "Triglycerides", parameter: "Triglycerides", unit: "mg/dL", normalMin: 0, normalMax: 150, description: "Serum triglycerides" },
    { id: "biochem_9",  name: "Liver Function Test - ALT (SGPT)", parameter: "ALT", unit: "U/L", normalMin: 7, normalMax: 56, description: "Alanine transaminase" },
    { id: "biochem_10", name: "Liver Function Test - AST (SGOT)", parameter: "AST", unit: "U/L", normalMin: 10, normalMax: 40, description: "Aspartate transaminase" },
    { id: "biochem_11", name: "Alkaline Phosphatase (ALP)", parameter: "ALP", unit: "U/L", normalMin: 44, normalMax: 147, description: "Bone & liver enzyme" },
    { id: "biochem_12", name: "Gamma GT (GGT)", parameter: "GGT", unit: "U/L", normalMin: 9, normalMax: 48, description: "Gamma-glutamyl transferase" },
    { id: "biochem_13", name: "Total Bilirubin", parameter: "Bilirubin (Total)", unit: "mg/dL", normalMin: 0.3, normalMax: 1.2, description: "Total bilirubin" },
    { id: "biochem_14", name: "Direct Bilirubin", parameter: "Bilirubin (Direct)", unit: "mg/dL", normalMin: 0, normalMax: 0.3, description: "Direct bilirubin" },
    { id: "biochem_15", name: "Indirect Bilirubin", parameter: "Bilirubin (Indirect)", unit: "mg/dL", normalMin: 0.2, normalMax: 0.9, description: "Indirect bilirubin" },
    { id: "biochem_16", name: "Serum Albumin", parameter: "Albumin", unit: "g/dL", normalMin: 3.4, normalMax: 5.4, description: "Plasma albumin" },
    { id: "biochem_17", name: "Serum Globulin", parameter: "Globulin", unit: "g/dL", normalMin: 2, normalMax: 3.5, description: "Serum globulin proteins" },
    { id: "biochem_18", name: "Albumin/Globulin Ratio", parameter: "A/G Ratio", unit: "", normalMin: 1, normalMax: 2, description: "A/G ratio" },
    { id: "biochem_19", name: "Serum Total Protein", parameter: "Total Protein", unit: "g/dL", normalMin: 6, normalMax: 8.3, description: "Total serum protein" },
    { id: "biochem_20", name: "Urea", parameter: "Urea", unit: "mg/dL", normalMin: 10, normalMax: 50, description: "Serum urea" },
    { id: "biochem_21", name: "Serum Creatinine", parameter: "Creatinine", unit: "mg/dL", normalMin: 0.6, normalMax: 1.3, description: "Renal function marker" },
    { id: "biochem_22", name: "Uric Acid", parameter: "Uric Acid", unit: "mg/dL", normalMin: 3.5, normalMax: 7.2, description: "Serum uric acid" },
    { id: "biochem_23", name: "Serum Calcium", parameter: "Calcium", unit: "mg/dL", normalMin: 8.5, normalMax: 10.5, description: "Calcium in blood" },
    { id: "biochem_24", name: "Serum Phosphorus", parameter: "Phosphorus", unit: "mg/dL", normalMin: 2.5, normalMax: 4.5, description: "Inorganic phosphorus" },
    { id: "biochem_25", name: "Serum Magnesium", parameter: "Magnesium", unit: "mg/dL", normalMin: 1.7, normalMax: 2.2, description: "Magnesium in serum" },
    { id: "biochem_26", name: "Serum Sodium (Na+)", parameter: "Sodium", unit: "mmol/L", normalMin: 135, normalMax: 145, description: "Serum sodium" },
    { id: "biochem_27", name: "Serum Potassium (K+)", parameter: "Potassium", unit: "mmol/L", normalMin: 3.5, normalMax: 5.1, description: "Serum potassium" },
    { id: "biochem_28", name: "Serum Chloride (Cl-)", parameter: "Chloride", unit: "mmol/L", normalMin: 98, normalMax: 107, description: "Serum chloride" },
    { id: "biochem_29", name: "Serum Bicarbonate (HCO3-)", parameter: "Bicarbonate", unit: "mmol/L", normalMin: 22, normalMax: 28, description: "Serum bicarbonate" },
    { id: "biochem_30", name: "Serum Iron", parameter: "Iron", unit: "µg/dL", normalMin: 60, normalMax: 170, description: "Iron concentration" },
    { id: "biochem_31", name: "Total Iron Binding Capacity (TIBC)", parameter: "TIBC", unit: "µg/dL", normalMin: 240, normalMax: 450, description: "Total iron binding capacity" },
    { id: "biochem_32", name: "Transferrin Saturation", parameter: "Transferrin Sat", unit: "%", normalMin: 20, normalMax: 50, description: "Iron/TIBC ratio" },
    { id: "biochem_33", name: "Serum Ferritin", parameter: "Ferritin", unit: "ng/mL", normalMin: 24, normalMax: 336, description: "Iron storage protein" },
    { id: "biochem_34", name: "Serum Amylase", parameter: "Amylase", unit: "U/L", normalMin: 30, normalMax: 110, description: "Pancreatic enzyme" },
    { id: "biochem_35", name: "Serum Lipase", parameter: "Lipase", unit: "U/L", normalMin: 23, normalMax: 300, description: "Pancreatic lipase" },
    { id: "biochem_36", name: "Lactate Dehydrogenase (LDH)", parameter: "LDH", unit: "U/L", normalMin: 140, normalMax: 280, description: "LDH enzyme activity" },
    { id: "biochem_37", name: "Creatine Kinase (CK)", parameter: "CK", unit: "U/L", normalMin: 22, normalMax: 198, description: "Creatine kinase enzyme" },
    { id: "biochem_38", name: "Creatine Kinase-MB (CK-MB)", parameter: "CK-MB", unit: "U/L", normalMin: 0, normalMax: 25, description: "Cardiac muscle CK isoenzyme" },
    { id: "biochem_39", name: "Troponin I (Qualitative)", parameter: "Troponin I", unit: "", normalMin: 0, normalMax: 0, description: "Cardiac biomarker (positive/negative)" },
    { id: "biochem_40", name: "Troponin T (Qualitative)", parameter: "Troponin T", unit: "", normalMin: 0, normalMax: 0, description: "Cardiac biomarker (positive/negative)" }
  ]
};

// Example: to integrate, push into your departments array like:
// departmentsArray.push(biochemistry);
// Microbiology — 40 tests
const microbiology = {
  id: "microbiology",
  name: "Microbiology",
  tests: [
    { id: "micro_1", name: "Blood Culture", parameter: "Bacterial Growth", unit: "", normalMin: 0, normalMax: 0, description: "Detection of bacteria in blood" },
    { id: "micro_2", name: "Urine Culture & Sensitivity", parameter: "Pathogen Growth", unit: "", normalMin: 0, normalMax: 0, description: "Urine culture and antibiotic sensitivity" },
    { id: "micro_3", name: "Stool Culture", parameter: "Pathogen Growth", unit: "", normalMin: 0, normalMax: 0, description: "Isolation of enteric pathogens" },
    { id: "micro_4", name: "Sputum Culture", parameter: "Pathogen Growth", unit: "", normalMin: 0, normalMax: 0, description: "Respiratory culture for TB or bacteria" },
    { id: "micro_5", name: "Throat Swab Culture", parameter: "Bacterial Growth", unit: "", normalMin: 0, normalMax: 0, description: "Throat swab culture" },
    { id: "micro_6", name: "Wound Swab Culture", parameter: "Bacterial Growth", unit: "", normalMin: 0, normalMax: 0, description: "Wound pus culture" },
    { id: "micro_7", name: "CSF Culture", parameter: "Pathogen Growth", unit: "", normalMin: 0, normalMax: 0, description: "Cerebrospinal fluid culture" },
    { id: "micro_8", name: "Ear Swab Culture", parameter: "Pathogen Growth", unit: "", normalMin: 0, normalMax: 0, description: "Otitis media pathogens" },
    { id: "micro_9", name: "Eye Swab Culture", parameter: "Pathogen Growth", unit: "", normalMin: 0, normalMax: 0, description: "Conjunctival swab culture" },
    { id: "micro_10", name: "High Vaginal Swab (HVS) Culture", parameter: "Pathogen Growth", unit: "", normalMin: 0, normalMax: 0, description: "Vaginal swab for infections" },
    { id: "micro_11", name: "Endocervical Swab Culture", parameter: "Pathogen Growth", unit: "", normalMin: 0, normalMax: 0, description: "STD related bacteria" },
    { id: "micro_12", name: "Anaerobic Culture", parameter: "Anaerobic Growth", unit: "", normalMin: 0, normalMax: 0, description: "Anaerobic bacteria isolation" },
    { id: "micro_13", name: "Fungal Culture", parameter: "Fungal Growth", unit: "", normalMin: 0, normalMax: 0, description: "Detection of fungi" },
    { id: "micro_14", name: "AFB Culture (Mycobacterium)", parameter: "AFB Growth", unit: "", normalMin: 0, normalMax: 0, description: "TB culture" },
    { id: "micro_15", name: "AFB Smear (Ziehl-Neelsen)", parameter: "AFB Smear", unit: "", normalMin: 0, normalMax: 0, description: "Microscopy for acid-fast bacilli" },
    { id: "micro_16", name: "Gram Stain (Microscopy)", parameter: "Gram Stain", unit: "", normalMin: 0, normalMax: 0, description: "Microscopic evaluation" },
    { id: "micro_17", name: "KOH Preparation (Fungal)", parameter: "KOH Mount", unit: "", normalMin: 0, normalMax: 0, description: "Fungal microscopy" },
    { id: "micro_18", name: "Malaria Parasite (MP) Smear", parameter: "Parasite Detection", unit: "", normalMin: 0, normalMax: 0, description: "Thick and thin smear" },
    { id: "micro_19", name: "Blood Parasite Smear", parameter: "Parasite Detection", unit: "", normalMin: 0, normalMax: 0, description: "Blood protozoa" },
    { id: "micro_20", name: "Wet Mount (Vaginal Swab)", parameter: "Parasite Detection", unit: "", normalMin: 0, normalMax: 0, description: "Trichomonas vaginalis" },
    { id: "micro_21", name: "Salmonella Typhi Culture", parameter: "Typhoid Bacteria", unit: "", normalMin: 0, normalMax: 0, description: "Typhoid culture" },
    { id: "micro_22", name: "Shigella Culture", parameter: "Shigella Bacteria", unit: "", normalMin: 0, normalMax: 0, description: "Shigella isolation" },
    { id: "micro_23", name: "Vibrio Cholera Culture", parameter: "Vibrio Cholerae", unit: "", normalMin: 0, normalMax: 0, description: "Cholera isolation" },
    { id: "micro_24", name: "E. coli Culture", parameter: "E. coli Growth", unit: "", normalMin: 0, normalMax: 0, description: "Urinary/GI pathogen" },
    { id: "micro_25", name: "Staphylococcus aureus Culture", parameter: "S. aureus", unit: "", normalMin: 0, normalMax: 0, description: "MRSA detection" },
    { id: "micro_26", name: "Streptococcus Culture", parameter: "Streptococcus spp.", unit: "", normalMin: 0, normalMax: 0, description: "Strep throat or systemic" },
    { id: "micro_27", name: "Klebsiella Culture", parameter: "Klebsiella spp.", unit: "", normalMin: 0, normalMax: 0, description: "Klebsiella pneumoniae" },
    { id: "micro_28", name: "Pseudomonas Culture", parameter: "Pseudomonas spp.", unit: "", normalMin: 0, normalMax: 0, description: "Pseudomonas aeruginosa" },
    { id: "micro_29", name: "Candida Culture", parameter: "Candida spp.", unit: "", normalMin: 0, normalMax: 0, description: "Yeast/fungal infections" },
    { id: "micro_30", name: "Helicobacter pylori (Culture)", parameter: "H. pylori", unit: "", normalMin: 0, normalMax: 0, description: "Stomach infection bacteria" },
    { id: "micro_31", name: "Clostridium difficile (Culture)", parameter: "C. difficile", unit: "", normalMin: 0, normalMax: 0, description: "Antibiotic-associated diarrhea" },
    { id: "micro_32", name: "Campylobacter Culture", parameter: "Campylobacter spp.", unit: "", normalMin: 0, normalMax: 0, description: "GI pathogen isolation" },
    { id: "micro_33", name: "Legionella Culture", parameter: "Legionella spp.", unit: "", normalMin: 0, normalMax: 0, description: "Legionella pneumonia" },
    { id: "micro_34", name: "Listeria Culture", parameter: "Listeria spp.", unit: "", normalMin: 0, normalMax: 0, description: "Listeriosis bacteria" },
    { id: "micro_35", name: "Mycoplasma Culture", parameter: "Mycoplasma spp.", unit: "", normalMin: 0, normalMax: 0, description: "Mycoplasma pneumoniae" },
    { id: "micro_36", name: "Ureaplasma Culture", parameter: "Ureaplasma spp.", unit: "", normalMin: 0, normalMax: 0, description: "STD associated" },
    { id: "micro_37", name: "Chlamydia Culture", parameter: "Chlamydia spp.", unit: "", normalMin: 0, normalMax: 0, description: "Chlamydia trachomatis" },
    { id: "micro_38", name: "Neisseria Culture", parameter: "Neisseria spp.", unit: "", normalMin: 0, normalMax: 0, description: "N. gonorrhoeae or N. meningitidis" },
    { id: "micro_39", name: "Bordetella pertussis Culture", parameter: "B. pertussis", unit: "", normalMin: 0, normalMax: 0, description: "Whooping cough bacteria" },
    { id: "micro_40", name: "Brucella Culture", parameter: "Brucella spp.", unit: "", normalMin: 0, normalMax: 0, description: "Brucellosis detection" }
  ]
};

// Example: to integrate, push into your departments array like:
// departmentsArray.push(microbiology);
// Serology — 40 tests
const serology = {
  id: "serology",
  name: "Serology",
  tests: [
    { id: "sero_1", name: "Widal Test", parameter: "S. Typhi Antibodies", unit: "titer", normalMin: 0, normalMax: 1, description: "Typhoid fever screening" },
    { id: "sero_2", name: "ASO Titer", parameter: "Anti-streptolysin O", unit: "IU/mL", normalMin: 0, normalMax: 200, description: "Streptococcal infection marker" },
    { id: "sero_3", name: "Rheumatoid Factor (RF)", parameter: "RF", unit: "IU/mL", normalMin: 0, normalMax: 14, description: "Rheumatoid arthritis marker" },
    { id: "sero_4", name: "CRP (C-Reactive Protein)", parameter: "CRP", unit: "mg/L", normalMin: 0, normalMax: 5, description: "Inflammatory marker" },
    { id: "sero_5", name: "Anti-CCP", parameter: "Anti-CCP", unit: "U/mL", normalMin: 0, normalMax: 20, description: "Anti-cyclic citrullinated peptide" },
    { id: "sero_6", name: "VDRL (Syphilis Screening)", parameter: "VDRL", unit: "", normalMin: 0, normalMax: 0, description: "Syphilis test" },
    { id: "sero_7", name: "TPHA (Confirmatory Syphilis)", parameter: "TPHA", unit: "", normalMin: 0, normalMax: 0, description: "Treponema pallidum hemagglutination" },
    { id: "sero_8", name: "HIV 1/2 Screening", parameter: "HIV Antibodies", unit: "", normalMin: 0, normalMax: 0, description: "HIV antibody screening" },
    { id: "sero_9", name: "HBsAg (Hepatitis B Surface Antigen)", parameter: "HBsAg", unit: "", normalMin: 0, normalMax: 0, description: "Hepatitis B infection" },
    { id: "sero_10", name: "Anti-HBs (Hepatitis B Surface Antibody)", parameter: "Anti-HBs", unit: "IU/L", normalMin: 10, normalMax: 1000, description: "Hepatitis B immunity marker" },
    { id: "sero_11", name: "Anti-HBc (Total)", parameter: "Anti-HBc", unit: "", normalMin: 0, normalMax: 0, description: "Hepatitis B core antibody" },
    { id: "sero_12", name: "HBeAg", parameter: "HBeAg", unit: "", normalMin: 0, normalMax: 0, description: "Hepatitis B infectivity marker" },
    { id: "sero_13", name: "Anti-HBe", parameter: "Anti-HBe", unit: "", normalMin: 0, normalMax: 0, description: "Hepatitis B e antibody" },
    { id: "sero_14", name: "Anti-HCV", parameter: "Anti-HCV", unit: "", normalMin: 0, normalMax: 0, description: "Hepatitis C antibody" },
    { id: "sero_15", name: "HAV IgM", parameter: "HAV IgM", unit: "", normalMin: 0, normalMax: 0, description: "Acute Hepatitis A infection" },
    { id: "sero_16", name: "HAV IgG", parameter: "HAV IgG", unit: "", normalMin: 0, normalMax: 0, description: "Past Hepatitis A exposure" },
    { id: "sero_17", name: "HEV IgM", parameter: "HEV IgM", unit: "", normalMin: 0, normalMax: 0, description: "Acute Hepatitis E infection" },
    { id: "sero_18", name: "HEV IgG", parameter: "HEV IgG", unit: "", normalMin: 0, normalMax: 0, description: "Past Hepatitis E exposure" },
    { id: "sero_19", name: "Dengue NS1 Antigen", parameter: "NS1", unit: "", normalMin: 0, normalMax: 0, description: "Dengue early detection" },
    { id: "sero_20", name: "Dengue IgM Antibody", parameter: "Dengue IgM", unit: "", normalMin: 0, normalMax: 0, description: "Recent dengue infection" },
    { id: "sero_21", name: "Dengue IgG Antibody", parameter: "Dengue IgG", unit: "", normalMin: 0, normalMax: 0, description: "Past dengue infection" },
    { id: "sero_22", name: "Chikungunya IgM", parameter: "Chikungunya IgM", unit: "", normalMin: 0, normalMax: 0, description: "Acute chikungunya infection" },
    { id: "sero_23", name: "Chikungunya IgG", parameter: "Chikungunya IgG", unit: "", normalMin: 0, normalMax: 0, description: "Past chikungunya infection" },
    { id: "sero_24", name: "Zika Virus IgM", parameter: "Zika IgM", unit: "", normalMin: 0, normalMax: 0, description: "Zika acute infection" },
    { id: "sero_25", name: "Zika Virus IgG", parameter: "Zika IgG", unit: "", normalMin: 0, normalMax: 0, description: "Past Zika infection" },
    { id: "sero_26", name: "Leptospira IgM", parameter: "Leptospira IgM", unit: "", normalMin: 0, normalMax: 0, description: "Leptospirosis acute infection" },
    { id: "sero_27", name: "Leptospira IgG", parameter: "Leptospira IgG", unit: "", normalMin: 0, normalMax: 0, description: "Past leptospirosis" },
    { id: "sero_28", name: "Brucella IgM", parameter: "Brucella IgM", unit: "", normalMin: 0, normalMax: 0, description: "Acute brucellosis" },
    { id: "sero_29", name: "Brucella IgG", parameter: "Brucella IgG", unit: "", normalMin: 0, normalMax: 0, description: "Past brucellosis" },
    { id: "sero_30", name: "Toxoplasma IgM", parameter: "Toxoplasma IgM", unit: "", normalMin: 0, normalMax: 0, description: "Acute toxoplasmosis" },
    { id: "sero_31", name: "Toxoplasma IgG", parameter: "Toxoplasma IgG", unit: "", normalMin: 0, normalMax: 0, description: "Past toxoplasmosis" },
    { id: "sero_32", name: "Rubella IgM", parameter: "Rubella IgM", unit: "", normalMin: 0, normalMax: 0, description: "Acute rubella" },
    { id: "sero_33", name: "Rubella IgG", parameter: "Rubella IgG", unit: "", normalMin: 10, normalMax: 999, description: "Rubella immunity" },
    { id: "sero_34", name: "CMV IgM", parameter: "CMV IgM", unit: "", normalMin: 0, normalMax: 0, description: "Acute cytomegalovirus infection" },
    { id: "sero_35", name: "CMV IgG", parameter: "CMV IgG", unit: "", normalMin: 0, normalMax: 0, description: "Past cytomegalovirus infection" },
    { id: "sero_36", name: "EBV IgM", parameter: "EBV IgM", unit: "", normalMin: 0, normalMax: 0, description: "Acute Epstein-Barr infection" },
    { id: "sero_37", name: "EBV IgG", parameter: "EBV IgG", unit: "", normalMin: 0, normalMax: 0, description: "Past Epstein-Barr infection" },
    { id: "sero_38", name: "H. pylori IgM", parameter: "H. pylori IgM", unit: "", normalMin: 0, normalMax: 0, description: "Acute H. pylori infection" },
    { id: "sero_39", name: "H. pylori IgG", parameter: "H. pylori IgG", unit: "", normalMin: 0, normalMax: 0, description: "Past H. pylori infection" },
    { id: "sero_40", name: "ANA (Antinuclear Antibody)", parameter: "ANA", unit: "", normalMin: 0, normalMax: 0, description: "Autoimmune disease marker" }
  ]
};

// Example: to integrate, push into your departments array like:
// departmentsArray.push(serology);
// Immunology — 40 tests
const immunology = {
  id: "immunology",
  name: "Immunology",
  tests: [
    { id: "immuno_1", name: "IgG", parameter: "Immunoglobulin G", unit: "mg/dL", normalMin: 700, normalMax: 1600, description: "Major circulating antibody" },
    { id: "immuno_2", name: "IgA", parameter: "Immunoglobulin A", unit: "mg/dL", normalMin: 70, normalMax: 400, description: "Mucosal immunity antibody" },
    { id: "immuno_3", name: "IgM", parameter: "Immunoglobulin M", unit: "mg/dL", normalMin: 40, normalMax: 230, description: "Primary immune response antibody" },
    { id: "immuno_4", name: "IgE", parameter: "Immunoglobulin E", unit: "IU/mL", normalMin: 0, normalMax: 100, description: "Allergy marker antibody" },
    { id: "immuno_5", name: "IgD", parameter: "Immunoglobulin D", unit: "mg/dL", normalMin: 0, normalMax: 10, description: "B-cell receptor immunoglobulin" },
    { id: "immuno_6", name: "Complement C3", parameter: "C3", unit: "mg/dL", normalMin: 90, normalMax: 180, description: "Complement pathway protein" },
    { id: "immuno_7", name: "Complement C4", parameter: "C4", unit: "mg/dL", normalMin: 10, normalMax: 40, description: "Complement pathway protein" },
    { id: "immuno_8", name: "CH50", parameter: "Total Complement Activity", unit: "U/mL", normalMin: 23, normalMax: 46, description: "Overall complement function" },
    { id: "immuno_9", name: "CD3", parameter: "T-lymphocytes", unit: "%", normalMin: 60, normalMax: 85, description: "T cell marker" },
    { id: "immuno_10", name: "CD4", parameter: "Helper T cells", unit: "%", normalMin: 30, normalMax: 60, description: "HIV monitoring" },
    { id: "immuno_11", name: "CD8", parameter: "Cytotoxic T cells", unit: "%", normalMin: 15, normalMax: 40, description: "T cell cytotoxic function" },
    { id: "immuno_12", name: "CD4/CD8 Ratio", parameter: "T cell balance", unit: "", normalMin: 1, normalMax: 3, description: "Immune system balance" },
    { id: "immuno_13", name: "CD19", parameter: "B cells", unit: "%", normalMin: 5, normalMax: 20, description: "B cell marker" },
    { id: "immuno_14", name: "CD56", parameter: "NK cells", unit: "%", normalMin: 5, normalMax: 20, description: "Natural Killer cells" },
    { id: "immuno_15", name: "HLA-B27", parameter: "HLA-B27 Antigen", unit: "", normalMin: 0, normalMax: 0, description: "Ankylosing spondylitis marker" },
    { id: "immuno_16", name: "ANA (Antinuclear Antibody)", parameter: "ANA", unit: "", normalMin: 0, normalMax: 0, description: "Autoimmune disease marker" },
    { id: "immuno_17", name: "Anti-dsDNA", parameter: "Anti-dsDNA antibody", unit: "IU/mL", normalMin: 0, normalMax: 30, description: "SLE specific antibody" },
    { id: "immuno_18", name: "ENA Profile", parameter: "Extractable Nuclear Antigens", unit: "", normalMin: 0, normalMax: 0, description: "Autoantibody panel" },
    { id: "immuno_19", name: "Anti-Smith", parameter: "Anti-Sm", unit: "", normalMin: 0, normalMax: 0, description: "SLE marker" },
    { id: "immuno_20", name: "Anti-RNP", parameter: "Anti-RNP", unit: "", normalMin: 0, normalMax: 0, description: "Mixed connective tissue disease marker" },
    { id: "immuno_21", name: "Anti-SSA (Ro)", parameter: "Anti-SSA", unit: "", normalMin: 0, normalMax: 0, description: "Sjögren’s syndrome marker" },
    { id: "immuno_22", name: "Anti-SSB (La)", parameter: "Anti-SSB", unit: "", normalMin: 0, normalMax: 0, description: "Sjögren’s syndrome marker" },
    { id: "immuno_23", name: "Anti-Scl-70", parameter: "Anti-Scl-70", unit: "", normalMin: 0, normalMax: 0, description: "Scleroderma marker" },
    { id: "immuno_24", name: "Anti-Jo-1", parameter: "Anti-Jo-1", unit: "", normalMin: 0, normalMax: 0, description: "Polymyositis marker" },
    { id: "immuno_25", name: "Anti-Mitochondrial Antibody (AMA)", parameter: "AMA", unit: "", normalMin: 0, normalMax: 0, description: "Primary biliary cirrhosis marker" },
    { id: "immuno_26", name: "Anti-Smooth Muscle Antibody (ASMA)", parameter: "ASMA", unit: "", normalMin: 0, normalMax: 0, description: "Autoimmune hepatitis marker" },
    { id: "immuno_27", name: "Anti-Phospholipid Antibody", parameter: "aPL", unit: "", normalMin: 0, normalMax: 0, description: "Antiphospholipid syndrome marker" },
    { id: "immuno_28", name: "Anti-Cardiolipin IgG/IgM", parameter: "aCL", unit: "", normalMin: 0, normalMax: 0, description: "APS testing" },
    { id: "immuno_29", name: "Lupus Anticoagulant", parameter: "LAC", unit: "", normalMin: 0, normalMax: 0, description: "Antiphospholipid syndrome marker" },
    { id: "immuno_30", name: "ANCA (C-ANCA & P-ANCA)", parameter: "ANCA", unit: "", normalMin: 0, normalMax: 0, description: "Vasculitis marker" },
    { id: "immuno_31", name: "Anti-TPO", parameter: "Anti-thyroid peroxidase antibody", unit: "IU/mL", normalMin: 0, normalMax: 34, description: "Autoimmune thyroiditis marker" },
    { id: "immuno_32", name: "Anti-Tg", parameter: "Anti-thyroglobulin antibody", unit: "IU/mL", normalMin: 0, normalMax: 115, description: "Hashimoto’s thyroiditis marker" },
    { id: "immuno_33", name: "TSH Receptor Antibody", parameter: "TRAb", unit: "IU/L", normalMin: 0, normalMax: 1.75, description: "Graves’ disease marker" },
    { id: "immuno_34", name: "Islet Cell Antibody", parameter: "ICA", unit: "", normalMin: 0, normalMax: 0, description: "Type 1 diabetes marker" },
    { id: "immuno_35", name: "GAD Antibody", parameter: "Glutamic Acid Decarboxylase Ab", unit: "U/mL", normalMin: 0, normalMax: 5, description: "Type 1 diabetes marker" },
    { id: "immuno_36", name: "IA-2 Antibody", parameter: "Insulinoma Antigen-2 Ab", unit: "", normalMin: 0, normalMax: 0, description: "Type 1 diabetes marker" },
    { id: "immuno_37", name: "Anti-Insulin Antibody", parameter: "IAA", unit: "", normalMin: 0, normalMax: 0, description: "Type 1 diabetes marker" },
    { id: "immuno_38", name: "Beta-2 Glycoprotein Antibody", parameter: "β2GPI", unit: "", normalMin: 0, normalMax: 0, description: "APS marker" },
    { id: "immuno_39", name: "Anti-CCP", parameter: "Anti-cyclic citrullinated peptide", unit: "U/mL", normalMin: 0, normalMax: 20, description: "Rheumatoid arthritis marker" },
    { id: "immuno_40", name: "HLA Typing", parameter: "HLA alleles", unit: "", normalMin: 0, normalMax: 0, description: "Genetic immune typing" }
  ]
};

// Example: add to departments array
// departmentsArray.push(immunology);
// Histopathology & Cytology — 40 tests
const histopathology = {
  id: "histopathology",
  name: "Histopathology & Cytology",
  tests: [
    { id: "histo_1", name: "Fine Needle Aspiration Cytology (FNAC)", parameter: "Cytology", unit: "", normalMin: 0, normalMax: 0, description: "Microscopic exam of aspirated cells" },
    { id: "histo_2", name: "Pap Smear", parameter: "Cervical cytology", unit: "", normalMin: 0, normalMax: 0, description: "Screening for cervical cancer" },
    { id: "histo_3", name: "Urine Cytology", parameter: "Urinary cells", unit: "", normalMin: 0, normalMax: 0, description: "Detect malignancy in urinary tract" },
    { id: "histo_4", name: "Sputum Cytology", parameter: "Respiratory cells", unit: "", normalMin: 0, normalMax: 0, description: "Lung cancer screening" },
    { id: "histo_5", name: "Pleural Fluid Cytology", parameter: "Pleural cells", unit: "", normalMin: 0, normalMax: 0, description: "Detect malignant effusion" },
    { id: "histo_6", name: "Ascitic Fluid Cytology", parameter: "Ascitic cells", unit: "", normalMin: 0, normalMax: 0, description: "Malignancy detection in ascites" },
    { id: "histo_7", name: "CSF Cytology", parameter: "Cerebrospinal fluid cells", unit: "", normalMin: 0, normalMax: 0, description: "CNS malignancy/metastasis" },
    { id: "histo_8", name: "Bone Marrow Aspiration Cytology", parameter: "Marrow cells", unit: "", normalMin: 0, normalMax: 0, description: "Leukemia & marrow disorders" },
    { id: "histo_9", name: "Bone Marrow Biopsy", parameter: "Core biopsy", unit: "", normalMin: 0, normalMax: 0, description: "Histology of marrow architecture" },
    { id: "histo_10", name: "Endometrial Biopsy", parameter: "Endometrial tissue", unit: "", normalMin: 0, normalMax: 0, description: "Evaluate abnormal uterine bleeding" },
    { id: "histo_11", name: "Skin Biopsy", parameter: "Skin lesion tissue", unit: "", normalMin: 0, normalMax: 0, description: "Dermatological malignancy diagnosis" },
    { id: "histo_12", name: "Liver Biopsy", parameter: "Liver tissue", unit: "", normalMin: 0, normalMax: 0, description: "Cirrhosis, hepatitis, tumors" },
    { id: "histo_13", name: "Kidney Biopsy", parameter: "Renal tissue", unit: "", normalMin: 0, normalMax: 0, description: "Glomerulonephritis, nephropathy" },
    { id: "histo_14", name: "Lung Biopsy", parameter: "Lung tissue", unit: "", normalMin: 0, normalMax: 0, description: "Lung cancer diagnosis" },
    { id: "histo_15", name: "Breast Biopsy", parameter: "Breast tissue", unit: "", normalMin: 0, normalMax: 0, description: "Benign/malignant breast lesions" },
    { id: "histo_16", name: "Prostate Biopsy", parameter: "Prostate tissue", unit: "", normalMin: 0, normalMax: 0, description: "Prostate cancer evaluation" },
    { id: "histo_17", name: "Cervical Biopsy", parameter: "Cervical tissue", unit: "", normalMin: 0, normalMax: 0, description: "Cervical dysplasia/cancer" },
    { id: "histo_18", name: "Lymph Node Biopsy", parameter: "Lymph node tissue", unit: "", normalMin: 0, normalMax: 0, description: "Lymphoma & metastasis diagnosis" },
    { id: "histo_19", name: "Gastrointestinal Biopsy", parameter: "GI mucosa", unit: "", normalMin: 0, normalMax: 0, description: "Gastritis, IBD, carcinoma" },
    { id: "histo_20", name: "Esophageal Biopsy", parameter: "Esophageal tissue", unit: "", normalMin: 0, normalMax: 0, description: "GERD, Barrett’s, carcinoma" },
    { id: "histo_21", name: "Stomach Biopsy", parameter: "Gastric tissue", unit: "", normalMin: 0, normalMax: 0, description: "Ulcer, carcinoma" },
    { id: "histo_22", name: "Small Intestine Biopsy", parameter: "Intestinal mucosa", unit: "", normalMin: 0, normalMax: 0, description: "Celiac disease, IBD" },
    { id: "histo_23", name: "Colon Biopsy", parameter: "Colonic mucosa", unit: "", normalMin: 0, normalMax: 0, description: "Polyps, carcinoma" },
    { id: "histo_24", name: "Rectal Biopsy", parameter: "Rectal mucosa", unit: "", normalMin: 0, normalMax: 0, description: "Rectal carcinoma" },
    { id: "histo_25", name: "Pancreatic Biopsy", parameter: "Pancreatic tissue", unit: "", normalMin: 0, normalMax: 0, description: "Pancreatitis, carcinoma" },
    { id: "histo_26", name: "Thyroid Biopsy", parameter: "Thyroid tissue", unit: "", normalMin: 0, normalMax: 0, description: "Nodules, thyroid cancer" },
    { id: "histo_27", name: "Salivary Gland Biopsy", parameter: "Salivary tissue", unit: "", normalMin: 0, normalMax: 0, description: "Sjögren’s, tumors" },
    { id: "histo_28", name: "Oral Cavity Biopsy", parameter: "Oral mucosa", unit: "", normalMin: 0, normalMax: 0, description: "Oral cancer screening" },
    { id: "histo_29", name: "Tongue Biopsy", parameter: "Tongue tissue", unit: "", normalMin: 0, normalMax: 0, description: "Oral cancer, lesions" },
    { id: "histo_30", name: "Bladder Biopsy", parameter: "Bladder tissue", unit: "", normalMin: 0, normalMax: 0, description: "Bladder carcinoma" },
    { id: "histo_31", name: "Endoscopic Biopsy", parameter: "GI tract tissue", unit: "", normalMin: 0, normalMax: 0, description: "Endoscopy guided biopsy" },
    { id: "histo_32", name: "Frozen Section", parameter: "Intraoperative biopsy", unit: "", normalMin: 0, normalMax: 0, description: "Immediate surgical diagnosis" },
    { id: "histo_33", name: "Immunohistochemistry (IHC)", parameter: "Protein markers", unit: "", normalMin: 0, normalMax: 0, description: "Cancer & tumor typing" },
    { id: "histo_34", name: "Special Stains", parameter: "Histological stains", unit: "", normalMin: 0, normalMax: 0, description: "Pathology tissue differentiation" },
    { id: "histo_35", name: "Cytogenetics (FISH)", parameter: "Chromosomal analysis", unit: "", normalMin: 0, normalMax: 0, description: "Leukemia, lymphoma markers" },
    { id: "histo_36", name: "Bone Tumor Biopsy", parameter: "Bone tissue", unit: "", normalMin: 0, normalMax: 0, description: "Osteosarcoma, metastasis" },
    { id: "histo_37", name: "Soft Tissue Tumor Biopsy", parameter: "Soft tissue", unit: "", normalMin: 0, normalMax: 0, description: "Sarcomas diagnosis" },
    { id: "histo_38", name: "Brain Biopsy", parameter: "Brain tissue", unit: "", normalMin: 0, normalMax: 0, description: "Tumors, infections" },
    { id: "histo_39", name: "Eye Biopsy", parameter: "Ocular tissue", unit: "", normalMin: 0, normalMax: 0, description: "Retinoblastoma, melanoma" },
    { id: "histo_40", name: "Testicular Biopsy", parameter: "Testicular tissue", unit: "", normalMin: 0, normalMax: 0, description: "Infertility, malignancy" }
  ]
};

// Example: add to departments array
// departmentsArray.push(histopathology);
// Endocrinology (Hormones) — 40 tests
const endocrinology = {
  id: "endocrinology",
  name: "Endocrinology / Hormones",
  tests: [
    { id: "endo_1", name: "Thyroid Stimulating Hormone (TSH)", parameter: "TSH", unit: "µIU/mL", normalMin: 0.4, normalMax: 4.0, description: "Primary thyroid function test" },
    { id: "endo_2", name: "Free T4 (Thyroxine)", parameter: "Free T4", unit: "ng/dL", normalMin: 0.8, normalMax: 1.8, description: "Thyroid hormone" },
    { id: "endo_3", name: "Free T3 (Triiodothyronine)", parameter: "Free T3", unit: "pg/mL", normalMin: 2.3, normalMax: 4.2, description: "Thyroid hormone" },
    { id: "endo_4", name: "Total T4", parameter: "T4", unit: "µg/dL", normalMin: 4.5, normalMax: 11.2, description: "Total thyroxine" },
    { id: "endo_5", name: "Total T3", parameter: "T3", unit: "ng/dL", normalMin: 80, normalMax: 200, description: "Total triiodothyronine" },
    { id: "endo_6", name: "Reverse T3", parameter: "rT3", unit: "ng/dL", normalMin: 10, normalMax: 24, description: "Inactive thyroid hormone" },
    { id: "endo_7", name: "Thyroglobulin", parameter: "Tg", unit: "ng/mL", normalMin: 0, normalMax: 55, description: "Thyroid tumor marker" },
    { id: "endo_8", name: "Calcitonin", parameter: "Calcitonin", unit: "pg/mL", normalMin: 0, normalMax: 10, description: "Medullary thyroid carcinoma marker" },
    { id: "endo_9", name: "Parathyroid Hormone (PTH)", parameter: "PTH", unit: "pg/mL", normalMin: 10, normalMax: 65, description: "Calcium metabolism" },
    { id: "endo_10", name: "Vitamin D (25-OH)", parameter: "25-Hydroxy Vitamin D", unit: "ng/mL", normalMin: 30, normalMax: 100, description: "Bone health marker" },
    { id: "endo_11", name: "Vitamin D (1,25-OH)", parameter: "Calcitriol", unit: "pg/mL", normalMin: 18, normalMax: 78, description: "Active Vitamin D" },
    { id: "endo_12", name: "Cortisol (AM)", parameter: "Cortisol", unit: "µg/dL", normalMin: 6, normalMax: 23, description: "Adrenal function" },
    { id: "endo_13", name: "Cortisol (PM)", parameter: "Cortisol", unit: "µg/dL", normalMin: 3, normalMax: 16, description: "Adrenal function (evening)" },
    { id: "endo_14", name: "ACTH", parameter: "Adrenocorticotropic Hormone", unit: "pg/mL", normalMin: 10, normalMax: 60, description: "Pituitary-adrenal axis" },
    { id: "endo_15", name: "DHEA-S", parameter: "Dehydroepiandrosterone sulfate", unit: "µg/dL", normalMin: 35, normalMax: 430, description: "Adrenal androgen" },
    { id: "endo_16", name: "Aldosterone", parameter: "Aldosterone", unit: "ng/dL", normalMin: 4, normalMax: 31, description: "Adrenal hormone" },
    { id: "endo_17", name: "Renin Activity", parameter: "Renin", unit: "ng/mL/hr", normalMin: 0.5, normalMax: 3.3, description: "RAAS system marker" },
    { id: "endo_18", name: "Prolactin", parameter: "Prolactin", unit: "ng/mL", normalMin: 4.8, normalMax: 23, description: "Pituitary hormone" },
    { id: "endo_19", name: "FSH", parameter: "Follicle Stimulating Hormone", unit: "mIU/mL", normalMin: 3, normalMax: 12, description: "Reproductive hormone" },
    { id: "endo_20", name: "LH", parameter: "Luteinizing Hormone", unit: "mIU/mL", normalMin: 2, normalMax: 12, description: "Reproductive hormone" },
    { id: "endo_21", name: "Estradiol (E2)", parameter: "Estrogen", unit: "pg/mL", normalMin: 15, normalMax: 350, description: "Female reproductive hormone" },
    { id: "endo_22", name: "Progesterone", parameter: "Progesterone", unit: "ng/mL", normalMin: 0.2, normalMax: 25, description: "Pregnancy hormone" },
    { id: "endo_23", name: "Testosterone (Total)", parameter: "Testosterone", unit: "ng/dL", normalMin: 300, normalMax: 1000, description: "Male reproductive hormone" },
    { id: "endo_24", name: "Free Testosterone", parameter: "Free Testosterone", unit: "pg/mL", normalMin: 50, normalMax: 210, description: "Bioavailable testosterone" },
    { id: "endo_25", name: "Sex Hormone Binding Globulin (SHBG)", parameter: "SHBG", unit: "nmol/L", normalMin: 10, normalMax: 57, description: "Hormone transport protein" },
    { id: "endo_26", name: "Insulin (Fasting)", parameter: "Insulin", unit: "µIU/mL", normalMin: 2, normalMax: 25, description: "Glucose metabolism" },
    { id: "endo_27", name: "C-Peptide", parameter: "C-Peptide", unit: "ng/mL", normalMin: 0.5, normalMax: 2.0, description: "Insulin secretion marker" },
    { id: "endo_28", name: "Growth Hormone (GH)", parameter: "GH", unit: "ng/mL", normalMin: 0, normalMax: 10, description: "Pituitary hormone" },
    { id: "endo_29", name: "IGF-1", parameter: "Insulin-like Growth Factor-1", unit: "ng/mL", normalMin: 100, normalMax: 300, description: "Growth marker" },
    { id: "endo_30", name: "IGFBP-3", parameter: "IGF Binding Protein-3", unit: "µg/mL", normalMin: 3, normalMax: 7, description: "Growth hormone activity" },
    { id: "endo_31", name: "Human Chorionic Gonadotropin (hCG)", parameter: "hCG", unit: "mIU/mL", normalMin: 0, normalMax: 5, description: "Pregnancy hormone" },
    { id: "endo_32", name: "Anti-Müllerian Hormone (AMH)", parameter: "AMH", unit: "ng/mL", normalMin: 1, normalMax: 10, description: "Ovarian reserve marker" },
    { id: "endo_33", name: "Inhibin B", parameter: "Inhibin B", unit: "pg/mL", normalMin: 20, normalMax: 350, description: "Fertility marker" },
    { id: "endo_34", name: "Leptin", parameter: "Leptin", unit: "ng/mL", normalMin: 0.5, normalMax: 15, description: "Energy balance hormone" },
    { id: "endo_35", name: "Adiponectin", parameter: "Adiponectin", unit: "µg/mL", normalMin: 4, normalMax: 26, description: "Metabolic marker" },
    { id: "endo_36", name: "Ghrelin", parameter: "Ghrelin", unit: "pg/mL", normalMin: 100, normalMax: 1200, description: "Hunger hormone" },
    { id: "endo_37", name: "Melatonin", parameter: "Melatonin", unit: "pg/mL", normalMin: 10, normalMax: 80, description: "Sleep cycle hormone" },
    { id: "endo_38", name: "Oxytocin", parameter: "Oxytocin", unit: "pg/mL", normalMin: 1, normalMax: 20, description: "Social bonding hormone" },
    { id: "endo_39", name: "Vasopressin (ADH)", parameter: "Antidiuretic Hormone", unit: "pg/mL", normalMin: 1, normalMax: 5, description: "Water balance hormone" },
    { id: "endo_40", name: "Epinephrine/Norepinephrine", parameter: "Catecholamines", unit: "pg/mL", normalMin: 10, normalMax: 100, description: "Adrenal medulla hormones" }
  ]
};

// Example: add to departments array
// departmentsArray.push(endocrinology);
// Molecular Biology / PCR — 40 tests
const molecularBiology = {
  id: "molecular_biology",
  name: "Molecular Biology / PCR",
  tests: [
    { id: "mol_1", name: "COVID-19 PCR", parameter: "SARS-CoV-2 RNA", unit: "Detected/Not Detected", normalMin: 0, normalMax: 0, description: "Real-time PCR for COVID-19" },
    { id: "mol_2", name: "Influenza A PCR", parameter: "Influenza A RNA", unit: "Detected/Not Detected", normalMin: 0, normalMax: 0, description: "PCR for influenza A" },
    { id: "mol_3", name: "Influenza B PCR", parameter: "Influenza B RNA", unit: "Detected/Not Detected", normalMin: 0, normalMax: 0, description: "PCR for influenza B" },
    { id: "mol_4", name: "RSV PCR", parameter: "RSV RNA", unit: "Detected/Not Detected", normalMin: 0, normalMax: 0, description: "Respiratory syncytial virus" },
    { id: "mol_5", name: "Hepatitis B PCR (HBV DNA)", parameter: "HBV DNA", unit: "IU/mL", normalMin: 0, normalMax: 0, description: "Quantitative viral load" },
    { id: "mol_6", name: "Hepatitis C PCR (HCV RNA)", parameter: "HCV RNA", unit: "IU/mL", normalMin: 0, normalMax: 0, description: "Quantitative viral load" },
    { id: "mol_7", name: "HIV PCR (HIV RNA)", parameter: "HIV RNA", unit: "copies/mL", normalMin: 0, normalMax: 0, description: "HIV viral load" },
    { id: "mol_8", name: "CMV PCR", parameter: "Cytomegalovirus DNA", unit: "copies/mL", normalMin: 0, normalMax: 0, description: "Cytomegalovirus detection" },
    { id: "mol_9", name: "EBV PCR", parameter: "Epstein-Barr Virus DNA", unit: "copies/mL", normalMin: 0, normalMax: 0, description: "EBV viral load" },
    { id: "mol_10", name: "HSV-1 PCR", parameter: "HSV-1 DNA", unit: "Detected/Not Detected", normalMin: 0, normalMax: 0, description: "Herpes Simplex Virus type 1" },
    { id: "mol_11", name: "HSV-2 PCR", parameter: "HSV-2 DNA", unit: "Detected/Not Detected", normalMin: 0, normalMax: 0, description: "Herpes Simplex Virus type 2" },
    { id: "mol_12", name: "HPV PCR (High-Risk)", parameter: "HPV DNA", unit: "Detected/Not Detected", normalMin: 0, normalMax: 0, description: "Human Papillomavirus high risk types" },
    { id: "mol_13", name: "Mycobacterium Tuberculosis PCR", parameter: "TB DNA", unit: "Detected/Not Detected", normalMin: 0, normalMax: 0, description: "GeneXpert MTB/RIF assay" },
    { id: "mol_14", name: "Chlamydia trachomatis PCR", parameter: "Chlamydia DNA", unit: "Detected/Not Detected", normalMin: 0, normalMax: 0, description: "STI detection" },
    { id: "mol_15", name: "Neisseria gonorrhoeae PCR", parameter: "Gonorrhea DNA", unit: "Detected/Not Detected", normalMin: 0, normalMax: 0, description: "STI detection" },
    { id: "mol_16", name: "HPV Genotyping", parameter: "HPV DNA", unit: "Type Specific", normalMin: 0, normalMax: 0, description: "HPV strain detection" },
    { id: "mol_17", name: "Zika Virus PCR", parameter: "Zika RNA", unit: "Detected/Not Detected", normalMin: 0, normalMax: 0, description: "Zika virus detection" },
    { id: "mol_18", name: "Dengue PCR", parameter: "Dengue RNA", unit: "Detected/Not Detected", normalMin: 0, normalMax: 0, description: "Early dengue virus detection" },
    { id: "mol_19", name: "Malaria PCR", parameter: "Plasmodium DNA", unit: "Detected/Not Detected", normalMin: 0, normalMax: 0, description: "Molecular malaria test" },
    { id: "mol_20", name: "Leishmania PCR", parameter: "Leishmania DNA", unit: "Detected/Not Detected", normalMin: 0, normalMax: 0, description: "Leishmaniasis diagnosis" },
    { id: "mol_21", name: "Toxoplasma PCR", parameter: "Toxoplasma DNA", unit: "Detected/Not Detected", normalMin: 0, normalMax: 0, description: "Toxoplasmosis detection" },
    { id: "mol_22", name: "Rubella PCR", parameter: "Rubella RNA", unit: "Detected/Not Detected", normalMin: 0, normalMax: 0, description: "Congenital rubella detection" },
    { id: "mol_23", name: "Measles PCR", parameter: "Measles RNA", unit: "Detected/Not Detected", normalMin: 0, normalMax: 0, description: "Measles virus detection" },
    { id: "mol_24", name: "Mumps PCR", parameter: "Mumps RNA", unit: "Detected/Not Detected", normalMin: 0, normalMax: 0, description: "Mumps virus detection" },
    { id: "mol_25", name: "Adenovirus PCR", parameter: "Adenovirus DNA", unit: "Detected/Not Detected", normalMin: 0, normalMax: 0, description: "Respiratory adenovirus" },
    { id: "mol_26", name: "Enterovirus PCR", parameter: "Enterovirus RNA", unit: "Detected/Not Detected", normalMin: 0, normalMax: 0, description: "Polio/Echo viruses" },
    { id: "mol_27", name: "Norovirus PCR", parameter: "Norovirus RNA", unit: "Detected/Not Detected", normalMin: 0, normalMax: 0, description: "Gastroenteritis virus" },
    { id: "mol_28", name: "Rotavirus PCR", parameter: "Rotavirus RNA", unit: "Detected/Not Detected", normalMin: 0, normalMax: 0, description: "Childhood gastroenteritis" },
    { id: "mol_29", name: "Parvovirus B19 PCR", parameter: "Parvovirus DNA", unit: "Detected/Not Detected", normalMin: 0, normalMax: 0, description: "Parvovirus detection" },
    { id: "mol_30", name: "Bordetella pertussis PCR", parameter: "Pertussis DNA", unit: "Detected/Not Detected", normalMin: 0, normalMax: 0, description: "Whooping cough detection" },
    { id: "mol_31", name: "H. pylori PCR", parameter: "H. pylori DNA", unit: "Detected/Not Detected", normalMin: 0, normalMax: 0, description: "Stomach infection" },
    { id: "mol_32", name: "Clostridium difficile PCR", parameter: "C. diff DNA", unit: "Detected/Not Detected", normalMin: 0, normalMax: 0, description: "Antibiotic-associated diarrhea" },
    { id: "mol_33", name: "MRSA PCR", parameter: "MRSA DNA", unit: "Detected/Not Detected", normalMin: 0, normalMax: 0, description: "Methicillin-resistant Staphylococcus aureus" },
    { id: "mol_34", name: "VRE PCR", parameter: "VRE DNA", unit: "Detected/Not Detected", normalMin: 0, normalMax: 0, description: "Vancomycin-resistant Enterococcus" },
    { id: "mol_35", name: "Carbapenemase Genes PCR", parameter: "Resistance Genes", unit: "Detected/Not Detected", normalMin: 0, normalMax: 0, description: "Antibiotic resistance" },
    { id: "mol_36", name: "BRCA1 Mutation PCR", parameter: "BRCA1 Gene", unit: "Mutation Detected/Not Detected", normalMin: 0, normalMax: 0, description: "Breast cancer gene" },
    { id: "mol_37", name: "BRCA2 Mutation PCR", parameter: "BRCA2 Gene", unit: "Mutation Detected/Not Detected", normalMin: 0, normalMax: 0, description: "Breast cancer gene" },
    { id: "mol_38", name: "KRAS Mutation PCR", parameter: "KRAS Gene", unit: "Mutation Detected/Not Detected", normalMin: 0, normalMax: 0, description: "Colon/lung cancer marker" },
    { id: "mol_39", name: "EGFR Mutation PCR", parameter: "EGFR Gene", unit: "Mutation Detected/Not Detected", normalMin: 0, normalMax: 0, description: "Lung cancer marker" },
    { id: "mol_40", name: "BCR-ABL PCR", parameter: "BCR-ABL Fusion Gene", unit: "Detected/Not Detected", normalMin: 0, normalMax: 0, description: "CML diagnosis" }
  ]
};

// Example: add to departments array
// departmentsArray.push(molecularBiology);
// Toxicology — 40 tests
const toxicology = {
  id: "toxicology",
  name: "Toxicology / Drug & Poison Screening",
  tests: [
    { id: "tox_1", name: "Alcohol (Ethanol) Level", parameter: "Ethanol", unit: "mg/dL", normalMin: 0, normalMax: 10, description: "Alcohol intoxication test" },
    { id: "tox_2", name: "Methanol Level", parameter: "Methanol", unit: "mg/dL", normalMin: 0, normalMax: 0, description: "Methanol poisoning" },
    { id: "tox_3", name: "Isopropanol Level", parameter: "Isopropanol", unit: "mg/dL", normalMin: 0, normalMax: 0, description: "Toxic alcohol screen" },
    { id: "tox_4", name: "Acetaminophen (Paracetamol)", parameter: "Acetaminophen", unit: "µg/mL", normalMin: 10, normalMax: 30, description: "Overdose detection" },
    { id: "tox_5", name: "Salicylates (Aspirin)", parameter: "Salicylate", unit: "mg/dL", normalMin: 10, normalMax: 30, description: "Aspirin toxicity" },
    { id: "tox_6", name: "Barbiturates Screen", parameter: "Barbiturates", unit: "Positive/Negative", normalMin: 0, normalMax: 0, description: "Drug abuse screen" },
    { id: "tox_7", name: "Benzodiazepines Screen", parameter: "Benzodiazepines", unit: "Positive/Negative", normalMin: 0, normalMax: 0, description: "Drug abuse screen" },
    { id: "tox_8", name: "Cannabinoids (THC)", parameter: "THC", unit: "Positive/Negative", normalMin: 0, normalMax: 0, description: "Marijuana detection" },
    { id: "tox_9", name: "Cocaine", parameter: "Cocaine", unit: "Positive/Negative", normalMin: 0, normalMax: 0, description: "Cocaine detection" },
    { id: "tox_10", name: "Opiates", parameter: "Morphine/Codeine", unit: "Positive/Negative", normalMin: 0, normalMax: 0, description: "Opiate detection" },
    { id: "tox_11", name: "Methadone", parameter: "Methadone", unit: "Positive/Negative", normalMin: 0, normalMax: 0, description: "Synthetic opioid detection" },
    { id: "tox_12", name: "Amphetamines", parameter: "Amphetamines", unit: "Positive/Negative", normalMin: 0, normalMax: 0, description: "Stimulant detection" },
    { id: "tox_13", name: "MDMA (Ecstasy)", parameter: "MDMA", unit: "Positive/Negative", normalMin: 0, normalMax: 0, description: "Ecstasy detection" },
    { id: "tox_14", name: "Phencyclidine (PCP)", parameter: "PCP", unit: "Positive/Negative", normalMin: 0, normalMax: 0, description: "Hallucinogen detection" },
    { id: "tox_15", name: "Synthetic Cannabinoids (Spice/K2)", parameter: "Synthetic THC", unit: "Positive/Negative", normalMin: 0, normalMax: 0, description: "Designer drug detection" },
    { id: "tox_16", name: "Fentanyl", parameter: "Fentanyl", unit: "Positive/Negative", normalMin: 0, normalMax: 0, description: "Synthetic opioid detection" },
    { id: "tox_17", name: "Tricyclic Antidepressants", parameter: "TCA", unit: "Positive/Negative", normalMin: 0, normalMax: 0, description: "Overdose detection" },
    { id: "tox_18", name: "Carbamazepine", parameter: "Carbamazepine", unit: "µg/mL", normalMin: 4, normalMax: 12, description: "Toxicity monitoring" },
    { id: "tox_19", name: "Phenytoin", parameter: "Phenytoin", unit: "µg/mL", normalMin: 10, normalMax: 20, description: "Toxicity monitoring" },
    { id: "tox_20", name: "Valproic Acid", parameter: "Valproate", unit: "µg/mL", normalMin: 50, normalMax: 100, description: "Therapeutic drug monitoring" },
    { id: "tox_21", name: "Lithium", parameter: "Lithium", unit: "mEq/L", normalMin: 0.6, normalMax: 1.2, description: "Mood stabilizer monitoring" },
    { id: "tox_22", name: "Digoxin", parameter: "Digoxin", unit: "ng/mL", normalMin: 0.8, normalMax: 2.0, description: "Cardiac drug monitoring" },
    { id: "tox_23", name: "Theophylline", parameter: "Theophylline", unit: "µg/mL", normalMin: 10, normalMax: 20, description: "Drug toxicity screen" },
    { id: "tox_24", name: "Gentamicin", parameter: "Gentamicin", unit: "µg/mL", normalMin: 5, normalMax: 10, description: "Antibiotic monitoring" },
    { id: "tox_25", name: "Amikacin", parameter: "Amikacin", unit: "µg/mL", normalMin: 15, normalMax: 25, description: "Antibiotic monitoring" },
    { id: "tox_26", name: "Vancomycin", parameter: "Vancomycin", unit: "µg/mL", normalMin: 10, normalMax: 20, description: "Antibiotic monitoring" },
    { id: "tox_27", name: "Lead (Pb)", parameter: "Lead", unit: "µg/dL", normalMin: 0, normalMax: 5, description: "Heavy metal poisoning" },
    { id: "tox_28", name: "Mercury (Hg)", parameter: "Mercury", unit: "µg/L", normalMin: 0, normalMax: 10, description: "Toxic element detection" },
    { id: "tox_29", name: "Arsenic (As)", parameter: "Arsenic", unit: "µg/L", normalMin: 0, normalMax: 10, description: "Toxic element detection" },
    { id: "tox_30", name: "Cadmium (Cd)", parameter: "Cadmium", unit: "µg/L", normalMin: 0, normalMax: 5, description: "Heavy metal detection" },
    { id: "tox_31", name: "Cyanide", parameter: "Cyanide", unit: "µg/L", normalMin: 0, normalMax: 0, description: "Acute poisoning test" },
    { id: "tox_32", name: "Carbon Monoxide (Carboxyhemoglobin)", parameter: "COHb", unit: "%", normalMin: 0, normalMax: 5, description: "Toxic gas exposure" },
    { id: "tox_33", name: "Organophosphate Pesticides", parameter: "Cholinesterase Activity", unit: "U/L", normalMin: 4000, normalMax: 12000, description: "Pesticide poisoning" },
    { id: "tox_34", name: "Herbicide (Paraquat)", parameter: "Paraquat", unit: "Positive/Negative", normalMin: 0, normalMax: 0, description: "Toxic herbicide test" },
    { id: "tox_35", name: "Insecticide (DDT)", parameter: "DDT", unit: "Positive/Negative", normalMin: 0, normalMax: 0, description: "Banned chemical detection" },
    { id: "tox_36", name: "Mushroom Poisoning Panel", parameter: "Amatoxins", unit: "Positive/Negative", normalMin: 0, normalMax: 0, description: "Toxic mushroom toxins" },
    { id: "tox_37", name: "Snake Venom Detection", parameter: "Venom Antigen", unit: "Positive/Negative", normalMin: 0, normalMax: 0, description: "Envenomation test" },
    { id: "tox_38", name: "Scorpion Venom Detection", parameter: "Venom Antigen", unit: "Positive/Negative", normalMin: 0, normalMax: 0, description: "Envenomation test" },
    { id: "tox_39", name: "Therapeutic Drug Panel", parameter: "Multiple Drugs", unit: "Quantitative", normalMin: 0, normalMax: 0, description: "Routine drug monitoring" },
    { id: "tox_40", name: "Comprehensive Drug Abuse Panel", parameter: "Multi-drug", unit: "Positive/Negative", normalMin: 0, normalMax: 0, description: "Drug abuse screen (10–20 drugs)" }
  ]
};

// Example: add to departments array
// departmentsArray.push(toxicology);
// Genetics / DNA Testing — 40 tests
const genetics = {
  id: "genetics",
  name: "Genetics / DNA Testing",
  tests: [
    { id: "gen_1", name: "Karyotyping", parameter: "Chromosome Analysis", unit: "Normal/Abnormal", normalMin: 0, normalMax: 0, description: "Detects chromosomal abnormalities" },
    { id: "gen_2", name: "FISH Test", parameter: "Fluorescence In Situ Hybridization", unit: "Normal/Abnormal", normalMin: 0, normalMax: 0, description: "Gene rearrangement detection" },
    { id: "gen_3", name: "Down Syndrome Screening (Trisomy 21)", parameter: "Chromosome 21", unit: "Normal/Abnormal", normalMin: 0, normalMax: 0, description: "Genetic disorder detection" },
    { id: "gen_4", name: "Turner Syndrome (XO)", parameter: "Sex Chromosome", unit: "Normal/Abnormal", normalMin: 0, normalMax: 0, description: "Female chromosomal abnormality" },
    { id: "gen_5", name: "Klinefelter Syndrome (XXY)", parameter: "Sex Chromosome", unit: "Normal/Abnormal", normalMin: 0, normalMax: 0, description: "Male chromosomal abnormality" },
    { id: "gen_6", name: "BRCA1 Gene Mutation", parameter: "BRCA1", unit: "Mutation Detected/Not Detected", normalMin: 0, normalMax: 0, description: "Breast/ovarian cancer risk" },
    { id: "gen_7", name: "BRCA2 Gene Mutation", parameter: "BRCA2", unit: "Mutation Detected/Not Detected", normalMin: 0, normalMax: 0, description: "Breast/ovarian cancer risk" },
    { id: "gen_8", name: "CFTR Gene (Cystic Fibrosis)", parameter: "CFTR Mutation", unit: "Detected/Not Detected", normalMin: 0, normalMax: 0, description: "Cystic fibrosis diagnosis" },
    { id: "gen_9", name: "Sickle Cell Mutation (HbS)", parameter: "HBB Gene", unit: "Detected/Not Detected", normalMin: 0, normalMax: 0, description: "Sickle cell anemia detection" },
    { id: "gen_10", name: "Thalassemia Mutation Panel", parameter: "HBB Gene", unit: "Detected/Not Detected", normalMin: 0, normalMax: 0, description: "Beta thalassemia mutation detection" },
    { id: "gen_11", name: "Fragile X Syndrome", parameter: "FMR1 Gene", unit: "Detected/Not Detected", normalMin: 0, normalMax: 0, description: "Genetic intellectual disability" },
    { id: "gen_12", name: "Huntington’s Disease Gene Test", parameter: "HTT Gene", unit: "CAG Repeats", normalMin: 0, normalMax: 35, description: "Neurodegenerative disease" },
    { id: "gen_13", name: "Alzheimer’s APOE Genotyping", parameter: "APOE Gene", unit: "Alleles", normalMin: 0, normalMax: 0, description: "Alzheimer’s risk factor" },
    { id: "gen_14", name: "Parkinson’s LRRK2 Mutation", parameter: "LRRK2 Gene", unit: "Mutation", normalMin: 0, normalMax: 0, description: "Genetic Parkinson’s disease" },
    { id: "gen_15", name: "Spinal Muscular Atrophy (SMA)", parameter: "SMN1 Gene", unit: "Mutation", normalMin: 0, normalMax: 0, description: "Neuromuscular disorder" },
    { id: "gen_16", name: "Duchenne Muscular Dystrophy (DMD)", parameter: "DMD Gene", unit: "Mutation", normalMin: 0, normalMax: 0, description: "Muscle degeneration disorder" },
    { id: "gen_17", name: "Hemophilia A (Factor VIII Gene)", parameter: "F8 Gene", unit: "Mutation", normalMin: 0, normalMax: 0, description: "Blood clotting disorder" },
    { id: "gen_18", name: "Hemophilia B (Factor IX Gene)", parameter: "F9 Gene", unit: "Mutation", normalMin: 0, normalMax: 0, description: "Blood clotting disorder" },
    { id: "gen_19", name: "Wilson’s Disease Gene", parameter: "ATP7B Gene", unit: "Mutation", normalMin: 0, normalMax: 0, description: "Copper metabolism disorder" },
    { id: "gen_20", name: "Marfan Syndrome Gene", parameter: "FBN1 Gene", unit: "Mutation", normalMin: 0, normalMax: 0, description: "Connective tissue disorder" },
    { id: "gen_21", name: "Polycystic Kidney Disease (PKD1/PKD2)", parameter: "PKD Genes", unit: "Mutation", normalMin: 0, normalMax: 0, description: "Inherited kidney disease" },
    { id: "gen_22", name: "Hereditary Hemochromatosis", parameter: "HFE Gene", unit: "Mutation", normalMin: 0, normalMax: 0, description: "Iron overload disorder" },
    { id: "gen_23", name: "Tay-Sachs Disease", parameter: "HEXA Gene", unit: "Mutation", normalMin: 0, normalMax: 0, description: "Lysosomal storage disorder" },
    { id: "gen_24", name: "G6PD Deficiency DNA Test", parameter: "G6PD Gene", unit: "Mutation", normalMin: 0, normalMax: 0, description: "Hemolytic anemia risk" },
    { id: "gen_25", name: "Color Blindness DNA Test", parameter: "OPN1LW/OPN1MW Genes", unit: "Mutation", normalMin: 0, normalMax: 0, description: "Genetic vision disorder" },
    { id: "gen_26", name: "Genetic Deafness Panel", parameter: "GJB2 & Others", unit: "Mutation", normalMin: 0, normalMax: 0, description: "Hereditary hearing loss" },
    { id: "gen_27", name: "Celiac Disease Gene Test", parameter: "HLA-DQ2/DQ8", unit: "Alleles", normalMin: 0, normalMax: 0, description: "Celiac disease susceptibility" },
    { id: "gen_28", name: "Multiple Sclerosis Gene Panel", parameter: "HLA-DRB1", unit: "Alleles", normalMin: 0, normalMax: 0, description: "MS genetic risk" },
    { id: "gen_29", name: "Obesity Gene Panel", parameter: "MC4R, FTO", unit: "Mutation", normalMin: 0, normalMax: 0, description: "Obesity risk detection" },
    { id: "gen_30", name: "Diabetes Genetic Risk Panel", parameter: "TCF7L2, KCNJ11", unit: "Mutation", normalMin: 0, normalMax: 0, description: "Type 1 & 2 diabetes risk" },
    { id: "gen_31", name: "Hypertension Genetic Risk Panel", parameter: "ACE, AGT", unit: "Mutation", normalMin: 0, normalMax: 0, description: "High BP genetic predisposition" },
    { id: "gen_32", name: "Coronary Artery Disease Panel", parameter: "9p21, APOE", unit: "Mutation", normalMin: 0, normalMax: 0, description: "Heart disease risk" },
    { id: "gen_33", name: "Thrombophilia Panel", parameter: "Factor V Leiden, Prothrombin", unit: "Mutation", normalMin: 0, normalMax: 0, description: "Clotting disorder risk" },
    { id: "gen_34", name: "Warfarin Sensitivity Test", parameter: "CYP2C9, VKORC1", unit: "Genotype", normalMin: 0, normalMax: 0, description: "Drug response genetics" },
    { id: "gen_35", name: "Pharmacogenomic Panel", parameter: "CYP450 Genes", unit: "Genotype", normalMin: 0, normalMax: 0, description: "Drug metabolism testing" },
    { id: "gen_36", name: "Forensic DNA Profiling", parameter: "STR Markers", unit: "Profile", normalMin: 0, normalMax: 0, description: "Individual identification" },
    { id: "gen_37", name: "Paternity Test", parameter: "STR Markers", unit: "Match/Non-Match", normalMin: 0, normalMax: 0, description: "Parental identification" },
    { id: "gen_38", name: "Ancestry DNA Test", parameter: "Genome-Wide SNPs", unit: "Profile", normalMin: 0, normalMax: 0, description: "Genetic ancestry analysis" },
    { id: "gen_39", name: "Whole Exome Sequencing (WES)", parameter: "Exons", unit: "Variants", normalMin: 0, normalMax: 0, description: "Protein-coding gene analysis" },
    { id: "gen_40", name: "Whole Genome Sequencing (WGS)", parameter: "Genome", unit: "Variants", normalMin: 0, normalMax: 0, description: "Complete genome analysis" }
  ]
};

// Example: add to departments array
// departmentsArray.push(genetics);
// General Pathology — 40 tests
const pathology = {
  id: "pathology",
  name: "General Pathology",
  tests: [
    { id: "path_1", name: "Complete Urinalysis", parameter: "Color, pH, Protein, Glucose", unit: "Various", normalMin: 0, normalMax: 0, description: "Routine urine test" },
    { id: "path_2", name: "Stool Routine Examination", parameter: "Parasites, Blood, Mucus", unit: "Presence/Absence", normalMin: 0, normalMax: 0, description: "Intestinal infection check" },
    { id: "path_3", name: "Stool Occult Blood", parameter: "Hemoglobin", unit: "Positive/Negative", normalMin: 0, normalMax: 0, description: "Hidden GI bleeding detection" },
    { id: "path_4", name: "Pregnancy Test (Urine hCG)", parameter: "hCG Hormone", unit: "Positive/Negative", normalMin: 0, normalMax: 0, description: "Pregnancy confirmation" },
    { id: "path_5", name: "Pregnancy Test (Serum hCG)", parameter: "hCG Hormone", unit: "mIU/mL", normalMin: 0, normalMax: 5, description: "Pregnancy confirmation (serum)" },
    { id: "path_6", name: "Body Fluid Cytology", parameter: "Cell Types", unit: "Normal/Abnormal", normalMin: 0, normalMax: 0, description: "Ascitic/Pleural fluid cell exam" },
    { id: "path_7", name: "Cerebrospinal Fluid (CSF) Analysis", parameter: "Protein, Glucose, Cells", unit: "Various", normalMin: 0, normalMax: 0, description: "Meningitis/neurological disorders" },
    { id: "path_8", name: "Sputum Examination", parameter: "Bacteria, WBC, RBC", unit: "Presence/Absence", normalMin: 0, normalMax: 0, description: "Respiratory infection check" },
    { id: "path_9", name: "Sputum AFB Smear", parameter: "Acid-Fast Bacilli", unit: "Positive/Negative", normalMin: 0, normalMax: 0, description: "Tuberculosis screening" },
    { id: "path_10", name: "Semen Analysis", parameter: "Count, Motility, Morphology", unit: "Various", normalMin: 15, normalMax: 200, description: "Male fertility test" },
    { id: "path_11", name: "Semen Culture", parameter: "Bacterial Growth", unit: "Positive/Negative", normalMin: 0, normalMax: 0, description: "Infection detection in semen" },
    { id: "path_12", name: "FNAC (Fine Needle Aspiration Cytology)", parameter: "Cell Morphology", unit: "Normal/Abnormal", normalMin: 0, normalMax: 0, description: "Tumor/cyst cytology" },
    { id: "path_13", name: "Pap Smear", parameter: "Cervical Cells", unit: "Normal/Abnormal", normalMin: 0, normalMax: 0, description: "Cervical cancer screening" },
    { id: "path_14", name: "Liver Function Panel (Pathology)", parameter: "Bilirubin, Enzymes", unit: "mg/dL, U/L", normalMin: 0, normalMax: 0, description: "Liver health assessment" },
    { id: "path_15", name: "Kidney Function Panel (Pathology)", parameter: "Urea, Creatinine", unit: "mg/dL", normalMin: 0, normalMax: 0, description: "Kidney health assessment" },
    { id: "path_16", name: "Urine Culture", parameter: "Bacterial Growth", unit: "Positive/Negative", normalMin: 0, normalMax: 0, description: "UTI detection" },
    { id: "path_17", name: "Stool Culture", parameter: "Bacterial Growth", unit: "Positive/Negative", normalMin: 0, normalMax: 0, description: "Intestinal pathogen detection" },
    { id: "path_18", name: "Pleural Fluid Analysis", parameter: "Protein, Glucose, Cells", unit: "Various", normalMin: 0, normalMax: 0, description: "Pleural effusion cause detection" },
    { id: "path_19", name: "Ascitic Fluid Analysis", parameter: "Protein, Albumin, Cells", unit: "Various", normalMin: 0, normalMax: 0, description: "Liver cirrhosis/infection" },
    { id: "path_20", name: "Pericardial Fluid Analysis", parameter: "Protein, Cells", unit: "Various", normalMin: 0, normalMax: 0, description: "Pericardial effusion diagnosis" },
    { id: "path_21", name: "Bone Marrow Aspiration", parameter: "Cell Morphology", unit: "Normal/Abnormal", normalMin: 0, normalMax: 0, description: "Blood/bone marrow disorders" },
    { id: "path_22", name: "Bone Marrow Biopsy", parameter: "Histology", unit: "Normal/Abnormal", normalMin: 0, normalMax: 0, description: "Leukemia/lymphoma evaluation" },
    { id: "path_23", name: "Wound Swab Microscopy", parameter: "Bacteria, Pus Cells", unit: "Presence/Absence", normalMin: 0, normalMax: 0, description: "Infection detection in wounds" },
    { id: "path_24", name: "Wound Culture", parameter: "Bacterial Growth", unit: "Positive/Negative", normalMin: 0, normalMax: 0, description: "Pathogen identification in wounds" },
    { id: "path_25", name: "Skin Scraping KOH Test", parameter: "Fungal Elements", unit: "Positive/Negative", normalMin: 0, normalMax: 0, description: "Fungal skin infection detection" },
    { id: "path_26", name: "Nail Scraping for Fungal Infection", parameter: "Fungal Hyphae", unit: "Positive/Negative", normalMin: 0, normalMax: 0, description: "Onychomycosis diagnosis" },
    { id: "path_27", name: "Hair Root Analysis", parameter: "Microscopy", unit: "Normal/Abnormal", normalMin: 0, normalMax: 0, description: "Hair loss disorder analysis" },
    { id: "path_28", name: "Fine Needle Biopsy (Any Organ)", parameter: "Cytology", unit: "Normal/Abnormal", normalMin: 0, normalMax: 0, description: "Tumor diagnosis" },
    { id: "path_29", name: "Skin Biopsy", parameter: "Histology", unit: "Normal/Abnormal", normalMin: 0, normalMax: 0, description: "Skin disorder diagnosis" },
    { id: "path_30", name: "Kidney Biopsy", parameter: "Histology", unit: "Normal/Abnormal", normalMin: 0, normalMax: 0, description: "Glomerular disease evaluation" },
    { id: "path_31", name: "Liver Biopsy", parameter: "Histology", unit: "Normal/Abnormal", normalMin: 0, normalMax: 0, description: "Chronic liver disease diagnosis" },
    { id: "path_32", name: "Lymph Node Biopsy", parameter: "Histology", unit: "Normal/Abnormal", normalMin: 0, normalMax: 0, description: "Lymphoma/tuberculosis detection" },
    { id: "path_33", name: "Endometrial Biopsy", parameter: "Histology", unit: "Normal/Abnormal", normalMin: 0, normalMax: 0, description: "Infertility/bleeding disorder" },
    { id: "path_34", name: "Prostate Biopsy", parameter: "Histology", unit: "Normal/Abnormal", normalMin: 0, normalMax: 0, description: "Prostate cancer diagnosis" },
    { id: "path_35", name: "Breast Biopsy", parameter: "Histology", unit: "Normal/Abnormal", normalMin: 0, normalMax: 0, description: "Breast cancer diagnosis" },
    { id: "path_36", name: "Thyroid Biopsy", parameter: "Histology", unit: "Normal/Abnormal", normalMin: 0, normalMax: 0, description: "Thyroid nodule evaluation" },
    { id: "path_37", name: "Cervical Biopsy", parameter: "Histology", unit: "Normal/Abnormal", normalMin: 0, normalMax: 0, description: "Cervical cancer evaluation" },
    { id: "path_38", name: "Gastric Biopsy", parameter: "Histology", unit: "Normal/Abnormal", normalMin: 0, normalMax: 0, description: "Gastric ulcer/cancer detection" },
    { id: "path_39", name: "Colonic Biopsy", parameter: "Histology", unit: "Normal/Abnormal", normalMin: 0, normalMax: 0, description: "Colorectal cancer evaluation" },
    { id: "path_40", name: "Bladder Biopsy", parameter: "Histology", unit: "Normal/Abnormal", normalMin: 0, normalMax: 0, description: "Bladder cancer evaluation" }
  ]
};

// Example: add to departments array
// departmentsArray.push(pathology);

